Nostr Wallet Connect/Dropdown Menu
HiveTalk/zaplist pull request #13
Opened 2024-09-22 01:10 UTC by TheWildHustle

**Title:** Add Nostr Wallet Connect and Dropdown Menu

**Description:** This pull request introduces two major features to the project:

1. **Nostr Wallet Connect**: Integration of Nostr wallet connectivity.
2. **Dropdown Menu**: Addition of a dropdown menu for enhanced navigation.

**Files Updated:**

- `public/index.html`: Updated to include the dropdown menu and wallet connect elements.
- `public/script.js`: Updated to handle the new dropdown menu and wallet connect functionalities.

**Files Added:**

- `src/wallet.js`: JavaScript implementation for wallet connectivity.
- `src/wallet.ts`: TypeScript definitions for wallet connectivity.
- `src/nip47.ts`: TypeScript definitions for NIP-47 protocol.
- `src/nip47.js`: JavaScript implementation for NIP-47 protocol.
- `src/app.ts`: TypeScript definitions for the main application logic.
- `src/app.js`: JavaScript implementation for the main application logic.

**Summary of Changes:**

- **Nostr Wallet Connect**:
    - Added wallet.js and wallet.ts for handling wallet connections.
    - Integrated NIP-47 protocol with nip47.js and nip47.ts.
- **Dropdown Menu**:
    - Updated index.html to include the dropdown menu structure.
    - Enhanced script.js to manage dropdown menu interactions.

![Zaplist 1](https://github.com/user-attachments/assets/0e723064-1bf2-4c28-9d33-c4b894c7d9ae)
![Zaplist 2](https://github.com/user-attachments/assets/415003cf-8d5d-43b4-b326-424c0ba39e73)
![Zaplist 3](https://github.com/user-attachments/assets/9c293049-f34f-44d2-a132-b1b7ee19c4b0)

**Testing:**

- Ensure that the dropdown menu is functional and responsive.
- Verify that the Nostr wallet connect feature works as expected.

2024-09-29 23:27 UTC, bitkarrot commented on public/index.html
> +
lets move the style to a separate CSS file

2024-09-29 23:27 UTC, bitkarrot commented on public/script.js
Lets rename script.js to something that is more descriptive to its function, for example if the logic is only for dropdown menu, then name the file to "menu.js" , and if there are other functions related to  wallet logic or nostr logic, split into a separate file and name accordingly. this way as a project grows in function, it  is easier to manage and clear

2024-09-29 23:27 UTC, bitkarrot commented on src/wallet.ts
I am not sure why you have duplicate .ts and .js unless this is meant as practice?

2024-09-29 23:28 UTC, bitkarrot requested changes
please make changes as per prior comments. thanks

2024-10-09 16:04 UTC, closed without merging

2024-10-09 18:10 UTC, bitkarrot commented
how's it going ?

2024-10-10 02:21 UTC, TheWildHustle commented
Broke wallet and login button functionality when moving files and folders around. 
But it looks like the imports have the correct routes.... 
I'll try to have it completed by tomorrow.

2024-10-11 03:33 UTC, bitkarrot commented
One of the things i noticed is the usage of custom css instead of the pico css framework. It might help to stick closer to the framework for some items so as less to modify and maintain. 

Also try separating and isolating out sections so that they are easily to comment out and you are able to focus on a new feature instead of carrying the weight of everything in the repo. Its a common stumbling block for new devs, which makes it harder to keep track of things as more is added and more technical debt is created.